name: crudfirebaseprueba
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  
  cloud_firestore: ^5.5.0
  firebase_analytics: ^11.3.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
